server:
  port: 9528
spring:
  application:
    name: sun-notice
  cloud:
    consul:
      host:
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 3600s
        heartbeat:
          enabled: true
  mail:
    username:
    password:
    default-encoding: utf-8
    host: smtp.qq.com