server:
  port: 9527
  servlet:
    context-path: /sun
spring:
  application:
    name: sun-platform
  cloud:
    consul:
      host: 121.4.162.107
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 3600s
        heartbeat:
          enabled: true