server:
  port: 9527
  servlet:
    context-path: /sun
spring:
  application:
    name: sun-platform
  cloud:
    consul:
      host: 121.4.162.107
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 3600s
        heartbeat:
          enabled: true
  datasource:
    username: root
    password: bxxd12345+
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.4.162.107:3306/sun?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl