server:
  port: 9526
spring:
  application:
    name: sun-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: sun-config
        health-check-interval: 3600s
        heartbeat:
          enabled: true
    config:
      server:
        native:
          search-locations: classpath:config
        bootstrap: true
  profiles:
    active: native