server:
  port: 9527
spring:
  application:
    name: sun-platform
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 3600s
        heartbeat:
          enabled: true
  datasource:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx:3306/sun?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
sun:
  mail:
    cron:
    to-address:
    from-address:
    birthday-text: