server:
  port: 8000
spring:
  application:
    name: sun-gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-interval: 3600s
        heartbeat:
          enabled: true
    gateway:
      routes:
      - id: route-platform
        uri: lb://sun-platform
        predicates:
        - Path=/sun/platform/**
        filters:
        - RewritePath=/sun/platform/(?<segment>.*), /$\{segment}
      - id: route-notice
        uri: lb://sun-notice
        predicates:
        - Path=/sun/notice/**
        filters:
        - RewritePath=/sun/notice/(?<segment>.*), /$\{segment}